app/config/routes.rb
Rails.application.routes.draw do
  get 'articles/new'

  get 'articles/show'

  get 'articles/edit'

  get 'articles/form'

  get 'articles/index'

  get 'welcome/show'
  

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :myforms
  resources :articles

end

app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/app/models/article.rb
class Article < ApplicationRecord
end

app/app/models/myform.rb
class Myform < ApplicationRecord
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
  end

  def show
  end

  def edit
  end

  def form
  end

  def index
  end
end

app/app/controllers/myforms_controller.rb
class MyformsController < ApplicationController
  before_action :set_myform, only: [:show, :edit, :update, :destroy]

  # GET /myforms
  # GET /myforms.json
  def index
    @myforms = Myform.all
  end

  # GET /myforms/1
  # GET /myforms/1.json
  def show
  end

  # GET /myforms/new
  def new
    @myform = Myform.new
  end

  # GET /myforms/1/edit
  def edit
  end

  # POST /myforms
  # POST /myforms.json
  def create
    @myform = Myform.new(myform_params)

    respond_to do |format|
      if @myform.save
        format.html { redirect_to @myform, notice: 'Myform was successfully created.' }
        format.json { render :show, status: :created, location: @myform }
      else
        format.html { render :new }
        format.json { render json: @myform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /myforms/1
  # PATCH/PUT /myforms/1.json
  def update
    respond_to do |format|
      if @myform.update(myform_params)
        format.html { redirect_to @myform, notice: 'Myform was successfully updated.' }
        format.json { render :show, status: :ok, location: @myform }
      else
        format.html { render :edit }
        format.json { render json: @myform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /myforms/1
  # DELETE /myforms/1.json
  def destroy
    @myform.destroy
    respond_to do |format|
      format.html { redirect_to myforms_url, notice: 'Myform was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_myform
      @myform = Myform.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def myform_params
      params.require(:myform).permit(:name, :email)
    end
end

app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def show
  end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/helpers/articles_helper.rb
module ArticlesHelper
end

app/app/helpers/myforms_helper.rb
module MyformsHelper
end

app/app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>

app/app/views/articles/form.html.erb
<h1>Articles#form</h1>
<p>Find me in app/views/articles/form.html.erb</p>

app/app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>

app/app/views/articles/new.html.erb
<h1>Articles#new</h1>
<p>Find me in app/views/articles/new.html.erb</p>

app/app/views/articles/show.html.erb
<h1>Articles#show</h1>
<p>Find me in app/views/articles/show.html.erb</p>

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/app/views/myforms/_form.html.erb
<%= form_for(myform) do |f| %>
  <% if myform.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(myform.errors.count, "error") %> prohibited this myform from being saved:</h2>

      <ul>
      <% myform.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/app/views/myforms/edit.html.erb
<h1>Editing Myform</h1>

<%= render 'form', myform: @myform %>

<%= link_to 'Show', @myform %> |
<%= link_to 'Back', myforms_path %>

app/app/views/myforms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Myforms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @myforms.each do |myform| %>
      <tr>
        <td><%= myform.name %></td>
        <td><%= myform.email %></td>
        <td><%= link_to 'Show', myform %></td>
        <td><%= link_to 'Edit', edit_myform_path(myform) %></td>
        <td><%= link_to 'Destroy', myform, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Myform', new_myform_path %>

app/app/views/myforms/new.html.erb
<h1>New Myform</h1>

<%= render 'form', myform: @myform %>

<%= link_to 'Back', myforms_path %>

app/app/views/myforms/show.html.erb
<p id="notice"><%= notice %></p>


<p>Hi, my name is <%= @myform.name %> and my email is <%= @myform.email %></p>







<%= link_to 'Edit', edit_myform_path(@myform) %> |
<%= link_to 'Back', myforms_path %>

app/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/app/views/welcome/show.html.erb
<h1>Welcome#show</h1>
<p>Find me in app/views/welcome/show.html.erb</p>